### ISSUE TITLE
Day 4 Column Check for Winner

### ISSUE THREAD

**Issue by TomKnightDev** [metalandcoffee/advent-of-code-2021#1]
![image](https://user-images.githubusercontent.com/6797436/145120258-4042a85a-d16a-4e2c-840d-c00d06bd9815.png)

Hey, so I think it might be the column check that's not working correctly.  I've not had much of a chance to debug it so I could be wrong :/

Also, I didn't see you debug in the browser today, so incase you're not aware, you can!   Just hit F12, go to the sources tab, then find the index.js file.  Add the break points on the left where the numbers are, refresh the page and you'll get all the values in memory at that point on the right.

Hope that helps!
Tom (Bolto720)

**Comment by metalandcoffee** [comment]
Thank you! The issue ended up being in the column logic for sure.
